name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout source
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js version
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'

    # Step 3: Install dependencies (optional, depending on your project)
    - name: Install dependencies
      run: npm install

    # Step 5: Deploy to Azure Web App
    - name: Deploy to Azure Web App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: testDeploymentApp1
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .